### ISSUE TITLE
Comments in LiveViewNative templates trigger a crash in iOS

### ISSUE THREAD

**Issue by seletz** [liveviewnative/liveview-client-swiftui#236]
While following the tutorial (Cats!), I added some HTML comments to a live template for iOS:

```
<list modifiers={[%{"type" => "navigation_title", "title" => "Cats!"}] |> Jason.encode!}>
   <!-- foo  -->
   <%= for {name, favorite} <- @cats_and_favorites do %>
        <hstack id={name}>
            <async-image src={"/images/cats/#{name}.jpg"}
                         modifiers='[
                             {
                             "type": "frame",
                             "width": 100,
                             "height": 100
                             }]' />
            <text><%= name %></text>
            <spacer />
            <button phx-click="toggle-favorite" phx-value-name={name}>
                <image system-name={if favorite, do: "star.fill", else: "star"}
                       symbol-color={if favorite, do: "#f3c51a", else: "#000000"}/>
            </button>
        </hstack>
   <% end %>
</list>
```

This triggers a panic in some rust crate:
```
thread '<unnamed>' panicked at 'unexpected token: Comment', crates/core/src/parser/mod.rs:43:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:88:58
stack backtrace:
   0:        0x10ceae726 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0c3e5871b1c1fed4
   1:        0x10cf00dea - core::fmt::write::hfa14499e54c39d2c
   2:        0x10cea0e1c - std::io::Write::write_fmt::h498b81e6ae5ee435
   3:        0x10ceae50a - std::sys_common::backtrace::print::h644aa7162d3d6fb7
   4:        0x10ceb1273 - std::panicking::default_hook::{{closure}}::hd0cac491d842c6a6
   5:        0x10ceb0f1a - std::panicking::default_hook::h4956ab915747cc40
   6:        0x10ceb1aee - std::panicking::rust_panic_with_hook::h42d02c8ac5153576
   7:        0x10ceb1833 - std::panicking::begin_panic_handler::{{closure}}::h8cb82a36b7db0cbc
   8:        0x10ceaebc8 - std::sys_common::backtrace::__rust_end_short_backtrace::hd01c800139124eb7
   9:        0x10ceb153d - _rust_begin_unwind
  10:        0x10cf2916a - core::panicking::panic_nounwind::h81f83ea4b32ba4a0
  11:        0x10cf29255 - core::panicking::panic_cannot_unwind::hd1bcd6b4ad8ecdd2
  12:        0x10cdcd091 - ___liveview_native_core$Document$parse
  13:        0x10cda3113 - $s18LiveViewNativeCore8DocumentC5parseyACxKAA9ToRustStrRzlFZAcA0hI0CKXEfU_
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-native-core-swift/Sources/LiveViewNativeCore/LiveViewNative.swift:94:26
  14:        0x10cdacbe3 - $sSS18LiveViewNativeCoreE9toRustStryxxAA0fG0CKXEKlFxSRys5UInt8VGKXEfU_
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-native-core-swift/Sources/LiveViewNativeCore/Support.swift:116:24
  15:        0x10cdadadc - $sSS18LiveViewNativeCoreE9toRustStryxxAA0fG0CKXEKlFxSRys5UInt8VGKXEfU_TA
  16:        0x10cdaceeb - $sSS8withUTF8yxxSRys5UInt8VGKXEKlF
  17:        0x10cdacab3 - $sSS18LiveViewNativeCoreE9toRustStryxxAA0fG0CKXEKlF
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-native-core-swift/Sources/LiveViewNativeCore/Support.swift:111:25
  18:        0x10cdacf4d - $sSS18LiveViewNativeCore9ToRustStrA2aBP02tofG0yqd__qd__AA0fG0CKXEKlFTW
  19:        0x10cda2fd7 - $s18LiveViewNativeCore8DocumentC5parseyACxKAA9ToRustStrRzlFZ
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-native-core-swift/Sources/LiveViewNativeCore/LiveViewNative.swift:92:24
  20:        0x10ca6278e - $s14LiveViewNative0aB11CoordinatorC17handleJoinPayload33_F40420C723E061B5980DD2022BC0C155LL08renderedG0ySDySSypG_tF
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-client-swiftui/Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift:374:58
  21:        0x10ca60710 - $s14LiveViewNative0aB11CoordinatorC07connectaB033_F40420C723E061B5980DD2022BC0C155LLyyYaKFyyYaYbScMYccfU4_TY0_
                               at /Users/seletz/Library/Developer/Xcode/DerivedData/CatsList-awtlzugqbjcbgxaujwhqmboejggc/SourcePackages/checkouts/liveview-client-swiftui/Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift:309:13
  22:     0x7ff835f774b6 - __ZN5swift34runJobInEstablishedExecutorContextEPNS_3JobE
  23:     0x7ff835f7824d - __ZL17swift_job_runImplPN5swift3JobENS_11ExecutorRefE
  24:        0x10fc3eaab - __dispatch_main_queue_drain
  25:        0x10fc3e790 - __dispatch_main_queue_callback_4CF
  26:     0x7ff800387b1f - ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  27:     0x7ff800382436 - ___CFRunLoopRun
  28:     0x7ff8003816a7 - _CFRunLoopRunSpecific
  29:     0x7ff809cb128a - _GSEventRunModal
  30:        0x117c54ad3 - -[UIApplication _run]
  31:        0x117c599ef - _UIApplicationMain
  32:        0x10eb8b667 - ___swift_memcpy93_8
  33:        0x10eb8b514 - ___swift_memcpy93_8
  34:        0x10e1ef7e9 - ___swift_memcpy195_8
  35:        0x10c99220e - $s8CatsList0aB3AppV5$mainyyFZ
                               at /Users/seletz/develop/elixir/lvn_tutorial/mobile/CatsList/CatsList/CatsListApp.swift:10:1
  36:        0x10c992299 - main
thread caused non-unwinding panic. aborting.
CoreSimulator 857.14 - Device: iPhone 14 Pro (F424D97C-244F-4053-9685-7213BE4EE276) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone
```

I know this is bleeding edge, I'm thrilled nevertheless! 💯 🥇

**Comment by seletz** [comment]
Hmm, I now realise that this issue should probably raised in the rust library.  Should it?

**Comment by carson-katri** [comment]
I think it would make sense being raised there, as it crashes during parsing.

Have you tried using the EEx comment syntax? I don't think this will ever make it to the client.
```html
<%!-- Some comment text here --%>
```

**Comment by bcardarella** [comment]
@carson-katri I believe the Core lib should be ignoring comments as part of the DOM it produces.

**Comment by bcardarella** [comment]
We can get a faster fix here for now but long-term this should be handled in Core IMO

**Comment by seletz** [comment]
@carson-katri Ok I'll remember to use the EEx comments for now.

So I'm trying to follow along the Cats tutorial -- It seems that tags have changed, i.e. `<asyncimage />` -> `<async-image />' etc, and `<navigationlink />` -> `<navigation-link />` (the latter implementation has been commented out in swift in the current master).

I guess you are aware and don't want issues for these.  Is there a tag / commit for which the tutorial works?  I have been able to work around / find out some stuff wrt LiveViewCoordinator/LiveSessionCoordinator-- again, bleeding edge, I know.

Again, I'm very thrilled to try this out and get back to full-stack again, so 👍

**Comment by carson-katri** [comment]
@seletz Documentation updates are being made in #198 

The naming scheme to go from SwiftUI View to tag is now `PascalCase` -> `kebab-case`. There are special cases for stacks, so `vstack` or `v-stack` is valid. However we plan on switching everything to use the original `PascalCase` name in the future once the Rust parser can support capitalization.

**Comment by AZholtkevych** [comment]
According to @shadowfacts blocked by the Core stuff

**Comment by AZholtkevych** [comment]
RUST bug, moving to Core board
